services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    image: mylab/laravel-frankenphp:latest
    container_name: laravel_app
    ports:
      - "${APP_PORT:-8100}:80"
      - "${XDEBUG_CLIENT_PORT:-9003}:9003"
    env_file:
      - .env
    volumes:
      - ./src:/app:delegated
      - caddydata:/data
    environment:
      - XDG_CONFIG_HOME=/home/appuser/.config
    depends_on:
      - db
      - redis
      - rabbitmq

  db:
    image: postgres:15
    container_name: "${DB_HOST:-pg_main}"
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${EXTERNAL_DB_PORT:-5457}:${DB_PORT:-5432}"
    volumes:
      - dbdata:/var/lib/postgresql/data
      - ./db/initdb:/docker-entrypoint-initdb.d:ro
    command: ["postgres", "-c", "shared_preload_libraries=pg_stat_statements"]  

  pgbouncer:
    image: bitnami/pgbouncer:latest
    container_name: pgbouncer
    depends_on:
      - db
    ports:
      - "${PGBOUNCER_LISTEN_PORT:-6432}:6432"
    volumes:
      # bitnami expects config files in /opt/bitnami/pgbouncer/conf
      - ./pgbouncer/pgbouncer.ini:/etc/pgbouncer/pgbouncer.ini:ro
      - ./pgbouncer/userlist.txt:/etc/pgbouncer/userlist.txt:ro
    environment:
      - POSTGRESQL_HOST="${DB_HOST:-pg_main}"
      - POSTGRESQL_PORT=${DB_PORT:-5432}
      - POSTGRESQL_DATABASE=${DB_DATABASE}
      - POSTGRESQL_USERNAME=${DB_USERNAME}
      - POSTGRESQL_PASSWORD=${DB_PASSWORD}
      - DATABASE_URL=postgresql://${DB_USERNAME}:${DB_PASSWORD}@db:5432/${DB_DATABASE}

  redis:
    image: redis:7
    container_name: redis
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - redisdata:/data

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    env_file:
      - .env
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
    ports:
      - "15672:15672"
      - "5672:5672"

  postgres_exporter:
    image: prometheuscommunity/postgres-exporter:latest
    container_name: postgres_exporter
    environment:
      - DATA_SOURCE_NAME=postgresql://${DB_USERNAME}:${DB_PASSWORD}@db:5432/${DB_DATABASE}?sslmode=disable
    ports:
      - "9187:9187"
    depends_on:
      - db

  node_exporter:
    image: prom/node-exporter:latest
    container_name: node_exporter
    ports:
      - "9100:9100"

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "${PROMETHEUS_PORT:-9091}:9090"
    depends_on:
      - postgres_exporter
      - node_exporter

  grafana:
    image: grafana/grafana:9.0.0
    container_name: grafana
    ports:
      - "${GRAFANA_PORT_EXTERNAL}:${GRAFANA_PORT:-3000}"
    environment:
      - "GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD:-secret}"
      - GF_USERS_ALLOW_SIGN_UP=false
    depends_on:
      - prometheus

volumes:
  dbdata:
  redisdata:
  caddydata:

networks:
  default:
    name: franken-laravel_default
    driver: bridge