services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    image: mylab/laravel-frankenphp:latest
    container_name: laravel_app
    ports:
      - "${APP_PORT:-8100}:80"
      - "${XDEBUG_CLIENT_PORT:-9003}:9003"
    env_file:
      - .env
    volumes:
      - ./src:/app:delegated
      - ./env:/app/.env:ro
      - caddydata:/data   # Caddy server data, required for FrankenPHP 
    environment:
      - XDG_CONFIG_HOME=/home/appuser/.config  # base path for configuration
    depends_on:
      - db
      - redis
      - rabbitmq

  db:
    image: postgres:15
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${EXTERNAL_DB_PORT}:${DB_PORT}"
    volumes:
      - dbdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - redisdata:/data

  rabbitmq:
    image: rabbitmq:3-management
    env_file:
      - .env
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
    ports:
      - "15672:15672"
      - "5672:5672"

  worker:
    image: mylab/laravel-frankenphp:latest
    depends_on:
      - app
      - db
      - redis
      - rabbitmq
    command: ["php", "/app/artisan", "queue:work", "--sleep=3", "--tries=3"]
    env_file:
      - .env
    volumes:
      - ./src:/app:delegated
      - ./env:/app/.env:ro
      - caddydata:/data

volumes:
  dbdata:
  redisdata:
  caddydata: